name: Run tests, build and releases on push to prod

on:
  push:
    branches:
      - "prod"

jobs:
  test_and_build:
    name: Test and Build
    uses: guidion-digital/node-workflows/.github/workflows/partial-test-build.yaml@0.0.2
    secrets: inherit
    with:
      concurrency_name: "${{github.ref}}"
      disable_linting: true
  release:
    name: Release
    uses: guidion-digital/node-workflows/.github/workflows/semantic-release.yaml@0.0.2
    needs: test_and_build
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      environment_name: "prod"